version: "3.8"
services:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bot:
    build: ./
    restart: always
    environment:
      DB_URL: jdbc:mariadb://db/bagana
      DB_USER: root
      DB_PASS: example
      BOT_TOKEN: token_placeholder
      CARD_URL: "http://cardmaker:8081/"
    depends_on:
      - db

  cardmaker:
    build: ./Brancoin-web-slim/bot/
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=root
      - POSTGRES_DB=bagana
      - DB_TYPE=mariadb+mariadbconnector
      - WEB_PORT=8081
    ports:
      - 8081:8081
    depends_on:
      - db
    volumes:
      - ./Brancoin-web-slim/bot/:/usr/src/app